In [70]:
from bs4 import BeautifulSoup, SoupStrainer
import requests
import re
import webbrowser
import pandas as pd

In [71]:
def latest_file():
    r = requests.get('http://www.gep.mtsss.gov.pt/indicadores-covid-19-mtsss')
    soup = BeautifulSoup(r.text, 'html.parser') 
    link = soup.findAll('a', attrs={'href': re.compile('/documents')})[0]
    #changing beautifulsoup object to string
    str_link = str(link)
    #extracting the link from object
    clean_link = re.findall('"([^"]*)"', str_link)[0]
    website = 'http://www.gep.mtsss.gov.pt'
    url = website+clean_link
    #transforming csv into dataframe
    data = pd.ExcelFile(url)
    all_my_sheets = pd.read_excel(data, sheet_name=None)
    #save down all worksheets separately
    for key in all_my_sheets: 
        all_my_sheets[key].to_csv('../original_files/%s.csv' %key,index=False)
    return all_my_sheets

In [72]:
latest_file()

{'Baixas por Isolamento':                    Nº DE BAIXAS POR ISOLAMENTO                 Unnamed: 1  \
 0                           por data de entrada                       NaN
 1                                           NaN                       NaN
 2    Nota: Situação da base de dados 22/07/2020                       NaN
 3                                           NaN                       NaN
 4                                           NaN  Nº Prestações Requeridas
 ..                                          ...                       ...
 184                                      202004                     28423
 185                                      202005                     28692
 186                                      202006                     25650
 187                                      202007                     12505
 188                            TOTAL (distinto)                     70858

     Unnamed: 2 Unnamed: 3
 0          NaN        NaN
 1          NaN        NaN
 2          NaN        NaN
 3          NaN        NaN
 4          NaN        NaN
 ..         ...        ...
 184      13544      14879
 185      15378      13314
 186      12043      13607
 187       7306       5199
 188      37665      33193

 [189 rows x 4 columns],
 'Apoio à Familia':     MEDIDA DE APOIO EXCECIONAL À FAMÍLIA PARA TRABALHADORES - NÚMERO DE PEDIDOS  \
 0                        por data de registo do pedido
 1                                                  NaN
 2           Nota: Situação da base de dados 22/07/2020
 3                                                  NaN
 4                              Mês de referência Março
 ..                                                 ...
 107                                                NaN
 108                      NÚMERO MÉDIO DE DIAS DE APOIO
 109                    Trabalhador por Conta de Outrem
 110                        Trabalhadores Independentes
 111                    Trabalhadores Servico Doméstico

     Unnamed: 1 Unnamed: 2  Unnamed: 3 Unnamed: 4 Unnamed: 5  Unnamed: 6  \
 0          NaN        NaN         NaN        NaN        NaN         NaN
 1          NaN        NaN         NaN        NaN        NaN         NaN
 2          NaN        NaN         NaN        NaN        NaN         NaN
 3          NaN        NaN         NaN        NaN        NaN         NaN
 4          NaN        NaN         NaN        NaN        NaN         NaN
 ..         ...        ...         ...        ...        ...         ...
 107        NaN        NaN         NaN        NaN        NaN         NaN
 108        NaN        NaN         NaN        NaN        NaN         NaN
 109        NaN    24.0938         NaN        NaN        NaN         NaN
 110        NaN    27.4685         NaN        NaN        NaN         NaN
 111        NaN    27.4885         NaN        NaN        NaN         NaN

     Unnamed: 7
 0          NaN
 1          NaN
 2          NaN
 3          NaN
 4          NaN
 ..         ...
 107        NaN
 108        NaN
 109        NaN
 110        NaN
 111        NaN

 [112 rows x 8 columns],
 'Apoio à Familia - Lançamentos':    MEDIDA DE APOIO EXCECIONAL À FAMÍLIA PARA TRABALHADORES - LANÇAMENTOS  \
 0                                                 NaN
 1          Nota: Situação da base de dados 22/07/2020
 2                                                 NaN
 3                               Por mês de referência
 4                                                 NaN
 5                                                 NaN
 6                         Trabalhador Conta de Outrem
 7                                                 NaN
 8                                                 NaN
 9                                                 NaN
 10                           Trabalhador Independente
 11                                                NaN
 12                                                NaN
 13                                                NaN
 14                                  Serviço Doméstico
 15                                                NaN
 16                                                NaN
 17                                                NaN
 18                                                NaN
 19                                                NaN
 20                                              TOTAL
 21                                                NaN
 22                                                NaN
 23                                                NaN
 24                    Trabalhador por Conta de Outrem
 25                           Trabalhador Independente
 26                                  Serviço Doméstico
 27                                                NaN
 28                                                NaN
 29                                   TOTAL - Por sexo
 30                                                NaN
 31                                                NaN
 32                                                NaN
 33                    Trabalhador por Conta de Outrem
 34                           Trabalhador Independente
 35                                  Serviço Doméstico

     Unnamed: 1          Unnamed: 2       Unnamed: 3  \
 0          NaN                 NaN              NaN
 1          NaN                 NaN              NaN
 2          NaN                 NaN              NaN
 3          NaN                 NaN              NaN
 4          NaN                 NaN              NaN
 5          NaN  Trabalhadores (nº)  Média Dias (nº)
 6     202003.0              143941          13.1119
 7     202004.0               83853          18.3684
 8     202005.0               81479          25.6996
 9     202006.0               41567          23.3842
 10    202003.0               16278          14.2872
 11    202004.0                7137          20.8146
 12    202005.0                7862          28.9551
 13    202006.0                3876          25.5114
 14    202003.0                1775          14.2269
 15    202004.0                1578          20.3517
 16    202005.0                1211          29.0619
 17    202006.0                 577          25.3397
 18         NaN                 NaN              NaN
 19         NaN                 NaN              NaN
 20         NaN                 NaN              NaN
 21         NaN                 NaN              NaN
 22         NaN               TOTAL              NaN
 23         NaN  Trabalhadores (nº)  Média Dias (nº)
 24         NaN              179347          18.5065
 25         NaN               18820          20.1304
 26         NaN                2362          20.8473
 27         NaN                 NaN              NaN
 28         NaN                 NaN              NaN
 29         NaN                 NaN              NaN
 30         NaN                 NaN              NaN
 31         NaN            FEMININO              NaN
 32         NaN  Trabalhadores (nº)  Média Dias (nº)
 33         NaN              145845          18.7213
 34         NaN               14518          20.2145
 35         NaN                2351          20.8534

                      Unnamed: 4       Unnamed: 5
 0                           NaN              NaN
 1                           NaN              NaN
 2                           NaN              NaN
 3                           NaN              NaN
 4                           NaN              NaN
 5   Entidades empregadoras (nº)              NaN
 6                         59095              NaN
 7                         39099              NaN
 8                         37613              NaN
 9                         22748              NaN
 10                          NaN              NaN
 11                          NaN              NaN
 12                          NaN              NaN
 13                          NaN              NaN
 14                          NaN              NaN
 15                          NaN              NaN
 16                          NaN              NaN
 17                          NaN              NaN
 18                          NaN              NaN
 19                          NaN              NaN
 20                          NaN              NaN
 21                          NaN              NaN
 22                          NaN              NaN
 23  Entidades empregadoras (nº)              NaN
 24                        70707              NaN
 25                            0              NaN
 26                            0              NaN
 27                          NaN              NaN
 28                          NaN              NaN
 29                          NaN              NaN
 30                          NaN              NaN
 31                    MASCULINO              NaN
 32           Trabalhadores (nº)  Média Dias (nº)
 33                        33502          17.4898
 34                         4302          19.8301
 35                           11             19.3  ,
 'Layoff – Estimativa ':    EEs QUE ENTREGARAM DOCUMENTO - COVID19 - Layoff Simplificado  \
 0              E COM REMUNERAÇÃO DECLARADA EM 2020-02
 1                                                 NaN
 2                                               Nota:
 3                                                 NaN
 4                                                 NaN
 ..                                                ...
 75                                                NaN
 76                                            Notas:
 77  podem existir divergências pouco significativa...
 78  a informação respeita aos trabalhadores e mass...
 79                                                NaN

                               Unnamed: 1 Unnamed: 2 Unnamed: 3
 0                                    NaN        NaN        NaN
 1                                    NaN        NaN        NaN
 2   Situação da base de dados 22/07/2020        NaN        NaN
 3                                    NaN        NaN        NaN
 4                                 Número        NaN        NaN
 ..                                   ...        ...        ...
 75                                   NaN        NaN        NaN
 76                                   NaN        NaN        NaN
 77                                   NaN        NaN        NaN
 78                                   NaN        NaN        NaN
 79                                   NaN        NaN        NaN

 [80 rows x 4 columns],
 'Layoff – Estim. - CAE,Dim,Dist':    EEs QUE ENTREGARAM DOCUMENTO - COVID19 - Layoff Simplificado  \
 0              E COM REMUNERAÇÃO DECLARADA EM 2020-02
 1                                             por CAE
 2                                                 NaN
 3                                              Nota:
 4                Situação da base de dados 22/07/2020
 5   Uma PS pode ter remunerações por várias NISS_E...
 6                                                 NaN
 7                                                 NaN
 8                                                 NaN
 9                                               TOTAL
 10                                                NaN
 11                                                  A
 12                                                  B
 13                                                  C
 14                                                  D
 15                                                  E
 16                                                  F
 17                                                  G
 18                                                  H
 19                                                  I
 20                                                  J
 21                                                  K
 22                                                  L
 23                                                  M
 24                                                  N
 25                                                  O
 26                                                  P
 27                                                  Q
 28                                                  R
 29                                                  S
 30                                              T + U
 31                                                NaN
 32                                            Notas:
 33  os totais podem ser divergentes, nomeadamente ...
 34  a informação respeita aos trabalhadores e mass...
 35                                                NaN
 36                                                NaN
 37                                                NaN
 38                                                NaN
 39                                                NaN
 40                                                NaN
 41                                                NaN
 42                                                NaN
 43                                                NaN
 44                                                NaN
 45                                                NaN
 46                                                NaN
 47                                                NaN
 48                                                NaN
 49                                                NaN
 50                                                NaN
 51                                                NaN
 52                                                NaN
 53                                                NaN
 54                                                NaN
 55                                                NaN
 56                                                NaN
 57                                                NaN

                                            Unnamed: 1  Unnamed: 2  \
 0                                                 NaN         NaN
 1                                                 NaN         NaN
 2                                                 NaN         NaN
 3                                                 NaN         NaN
 4                                                 NaN         NaN
 5                                                 NaN         NaN
 6                                                 NaN         NaN
 7                                                 NaN         NaN
 8                                                 NaN  Nº NISS_EE
 9                                                 NaN      114901
 10      PESSOAS SINGULARES COM TRABALHADORES A CARGO         5500
 11  Agricultura, produção animal, caça, floresta e...         885
 12                             Indústrias extractivas          64
 13                         Indústrias transformadoras       11587
 14  Electricidade, gás, vapor, água quente e fria ...          35
 15  Captação, tratamento e distribuição de água; s...         252
 16                                         Construção        3996
 17  Comércio por grosso e a retalho; reparação de ...       25527
 18                          Transportes e armazenagem        6686
 19                Alojamento, restauração e similares       25731
 20        Actividades de informação e de comunicação         1456
 21               Actividades financeiras e de seguros         385
 22                           Actividades imobiliárias        2544
 23  Actividades de consultoria, científicas, técni...        5424
 24  Actividades administrativas e dos serviços de ...        3756
 25  Administração pública e defesa; segurança soci...          47
 26                                           Educação        2770
 27         Actividades de saúde humana e apoio social        7987
 28  Actividades artísticas, de espectáculos, despo...        4601
 29                     Outras actividades de serviços        5664
 30  Actividades das famílias empregadoras de pesso...           4
 31                                                NaN         NaN
 32                                                NaN         NaN
 33                                                NaN         NaN
 34                                                NaN         NaN
 35                                                NaN         NaN
 36                                                NaN         NaN
 37                                                NaN         NaN
 38                                                NaN         NaN
 39                                                NaN         NaN
 40                                                NaN         NaN
 41                                                NaN         NaN
 42                                                NaN         NaN
 43                                                NaN         NaN
 44                                                NaN         NaN
 45                                                NaN         NaN
 46                                                NaN         NaN
 47                                                NaN         NaN
 48                                                NaN         NaN
 49                                                NaN         NaN
 50                                                NaN         NaN
 51                                                NaN         NaN
 52                                                NaN         NaN
 53                                                NaN         NaN
 54                                                NaN         NaN
 55                                                NaN         NaN
 56                                                NaN         NaN
 57                                                NaN         NaN

           Unnamed: 3        Unnamed: 4 Unnamed: 5  Unnamed: 6  \
 0                NaN               NaN        NaN         NaN
 1                NaN               NaN        NaN         NaN
 2                NaN               NaN        NaN         NaN
 3                NaN               NaN        NaN         NaN
 4                NaN               NaN        NaN         NaN
 5                NaN               NaN        NaN         NaN
 6                NaN         Por sexo:        NaN         NaN
 7                NaN  Nº TRABALHADORES        NaN         NaN
 8   Nº TRABALHADORES          Feminino  Masculino         NaN
 9            1379349            710736     668613         NaN
 10             10428              6938       3490         NaN
 11              7185              2779       4406         NaN
 12              1026               158        868         NaN
 13            309702            143124     166578         NaN
 14               644                93        551         NaN
 15              4037              1554       2483         NaN
 16             54533              7840      46693         NaN
 17            246595            120799     125796         NaN
 18             68519             17224      51295         NaN
 19            235835            130653     105182         NaN
 20             24561              9446      15115         NaN
 21              5272              2887       2385         NaN
 22             17009              9480       7529         NaN
 23             51108             25088      26020         NaN
 24            150268             83876      66392         NaN
 25              1316               427        889         NaN
 26             35151             27064       8087         NaN
 27             96211             83690      12521         NaN
 28             25591             11900      13691         NaN
 29             34338             25705       8633         NaN
 30                20                11          9         NaN
 31               NaN               NaN        NaN         NaN
 32               NaN               NaN        NaN         NaN
 33               NaN               NaN        NaN         NaN